# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cryptopp}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["J Smith"]
  s.date = %q{2010-03-16}
  s.description = %q{cryptopp is a cryptographic library for Ruby built on Wei Dai's Crypto++.}
  s.email = %q{dark.panda@gmail.com}
  s.extensions = ["ext/extconf.rb"]
  s.homepage = %q{http://github.com/dark-panda/cryptopp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{cryptopp is a cryptographic library for Ruby built on Wei Dai's Crypto++.}
  s.test_files = [
    "test/lib/test_helper.rb",
     "test/runner.rb",
     "test/test_ciphers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

