# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cryptopp}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["J Smith"]
  s.date = %q{2010-07-01}
  s.description = %q{cryptopp is a cryptographic library for Ruby built on Wei Dai's Crypto++.}
  s.email = %q{dark.panda@gmail.com}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "cryptopp.gemspec",
     "ext/.gitignore",
     "ext/Rakefile",
     "ext/ciphers.cpp",
     "ext/cryptopp.cpp",
     "ext/cryptopp_ruby_api.h",
     "ext/defs/block_modes.def",
     "ext/defs/checksums.def",
     "ext/defs/ciphers.def",
     "ext/defs/hashes.def",
     "ext/defs/hmacs.def",
     "ext/defs/paddings.def",
     "ext/defs/rngs.def",
     "ext/digests.cpp",
     "ext/extconf.rb",
     "ext/j3way.cpp",
     "ext/j3way.h",
     "ext/jadler32.h",
     "ext/jaes.cpp",
     "ext/jaes.h",
     "ext/jarc4.cpp",
     "ext/jarc4.h",
     "ext/jbase.cpp",
     "ext/jbase.h",
     "ext/jbasiccipherinfo.h",
     "ext/jblowfish.cpp",
     "ext/jblowfish.h",
     "ext/jcamellia.cpp",
     "ext/jcamellia.h",
     "ext/jcast128.cpp",
     "ext/jcast128.h",
     "ext/jcast256.cpp",
     "ext/jcast256.h",
     "ext/jcipher.cpp",
     "ext/jcipher.h",
     "ext/jcipher_t.h",
     "ext/jconfig.h",
     "ext/jconstants.h",
     "ext/jcrc32.h",
     "ext/jdes.cpp",
     "ext/jdes.h",
     "ext/jdes_ede2.cpp",
     "ext/jdes_ede2.h",
     "ext/jdes_ede3.cpp",
     "ext/jdes_ede3.h",
     "ext/jdes_xex3.cpp",
     "ext/jdes_xex3.h",
     "ext/jdiamond2.cpp",
     "ext/jdiamond2.h",
     "ext/jdiamond2lite.cpp",
     "ext/jdiamond2lite.h",
     "ext/jexception.h",
     "ext/jgost.cpp",
     "ext/jgost.h",
     "ext/jhash.cpp",
     "ext/jhash.h",
     "ext/jhash_t.h",
     "ext/jhaval.h",
     "ext/jhelpers.cpp",
     "ext/jhelpers.h",
     "ext/jhmac.cpp",
     "ext/jhmac.h",
     "ext/jhmac_t.h",
     "ext/jidea.cpp",
     "ext/jidea.h",
     "ext/jmarc4.cpp",
     "ext/jmarc4.h",
     "ext/jmars.cpp",
     "ext/jmars.h",
     "ext/jmd2.h",
     "ext/jmd4.h",
     "ext/jmd5.h",
     "ext/jpanamacipher.cpp",
     "ext/jpanamacipher.h",
     "ext/jpanamahash.h",
     "ext/jrc2.cpp",
     "ext/jrc2.h",
     "ext/jrc5.cpp",
     "ext/jrc5.h",
     "ext/jrc6.cpp",
     "ext/jrc6.h",
     "ext/jripemd160.h",
     "ext/jsafer.cpp",
     "ext/jsafer.h",
     "ext/jseal.cpp",
     "ext/jseal.h",
     "ext/jserpent.cpp",
     "ext/jserpent.h",
     "ext/jsha.h",
     "ext/jshacal2.cpp",
     "ext/jshacal2.h",
     "ext/jshark.cpp",
     "ext/jshark.h",
     "ext/jsink.cpp",
     "ext/jsink.h",
     "ext/jskipjack.cpp",
     "ext/jskipjack.h",
     "ext/jsquare.cpp",
     "ext/jsquare.h",
     "ext/jstream.cpp",
     "ext/jstream.h",
     "ext/jstream_t.h",
     "ext/jtea.cpp",
     "ext/jtea.h",
     "ext/jtiger.h",
     "ext/jtwofish.cpp",
     "ext/jtwofish.h",
     "ext/jwhirlpool.h",
     "ext/utils.cpp",
     "extras/parser_c.rb",
     "test/ciphers_test.rb",
     "test/data/ciphers/3desval.dat",
     "test/data/ciphers/3wayval.dat",
     "test/data/ciphers/arc4.dat",
     "test/data/ciphers/blowfish.dat",
     "test/data/ciphers/camellia.dat",
     "test/data/ciphers/cast128v.dat",
     "test/data/ciphers/cast256v.dat",
     "test/data/ciphers/descert.dat",
     "test/data/ciphers/diamond.dat",
     "test/data/ciphers/gostval.dat",
     "test/data/ciphers/ideaval.dat",
     "test/data/ciphers/marsval.dat",
     "test/data/ciphers/panamac.dat",
     "test/data/ciphers/rc2val.dat",
     "test/data/ciphers/rc5val.dat",
     "test/data/ciphers/rc6val.dat",
     "test/data/ciphers/rijndael.dat",
     "test/data/ciphers/saferval.dat",
     "test/data/ciphers/seal.dat",
     "test/data/ciphers/serpentv.dat",
     "test/data/ciphers/shacal2.dat",
     "test/data/ciphers/sharkval.dat",
     "test/data/ciphers/skipjack.dat",
     "test/data/ciphers/squareva.dat",
     "test/data/ciphers/twofishv.dat",
     "test/data/digests/adler32.dat",
     "test/data/digests/crc32.dat",
     "test/data/digests/haval.dat",
     "test/data/digests/havalcer.dat",
     "test/data/digests/md2.dat",
     "test/data/digests/md4.dat",
     "test/data/digests/md5.dat",
     "test/data/digests/panamah.dat",
     "test/data/digests/ripemd.dat",
     "test/data/digests/sha.dat",
     "test/data/digests/tiger.dat",
     "test/data/digests/whirlpool.dat",
     "test/data/hmacs/hmac.dat",
     "test/digests_test.rb",
     "test/hmacs_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/dark-panda/ruby-cryptopp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{cryptopp is a cryptographic library for Ruby built on Wei Dai's Crypto++.}
  s.test_files = [
    "test/ciphers_test.rb",
     "test/digests_test.rb",
     "test/hmacs_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

